# Code

In [ ]:
import random

class MBGDRegressor:
    
    def __init__(self,batch_size,learning_rate=0.01,epochs=100):
        
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs
        self.batch_size = batch_size
        
    def fit(self,X_train,y_train):
        # init your coefs
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])
        
        for i in range(self.epochs):
            
            for j in range(int(X_train.shape[0]/self.batch_size)):
                
                idx = random.sample(range(X_train.shape[0]),self.batch_size)
                
                y_hat = np.dot(X_train[idx],self.coef_) + self.intercept_
                #print("Shape of y_hat",y_hat.shape)
                intercept_der = -2 * np.mean(y_train[idx] - y_hat)
                self.intercept_ = self.intercept_ - (self.lr * intercept_der)

                coef_der = -2 * np.dot((y_train[idx] - y_hat),X_train[idx])
                self.coef_ = self.coef_ - (self.lr * coef_der)
        
        print(self.intercept_,self.coef_)
    
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

# Test

In [1]:
from sklearn.datasets import load_diabetes

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split as split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [3]:
X,y = load_diabetes(return_X_y = True)

In [4]:
X_train,X_test,y_train,y_test = split(X,y,train_size=0.8,random_state=42)

In [5]:
reg = LinearRegression()

In [6]:
reg.fit(X_train,y_train)
y_pred = reg.predict(X_test)
r2_score(y_test,y_pred)

0.45260660216173787

In [7]:
reg.intercept_

151.3456553477407

In [8]:
reg.coef_

array([  37.90031426, -241.96624835,  542.42575342,  347.70830529,
       -931.46126093,  518.04405547,  163.40353476,  275.31003837,
        736.18909839,   48.67112488])

In [10]:
gdr = MBGDRegressor(batch_size=35,epochs=1000,learning_rate = 0.5)

In [11]:
gdr.fit(X_train,y_train)

180.06339939684005 [  71.68789021 -229.52194655  551.75255898  375.85459157 -907.83305512
  520.18038116  146.36425249  304.00203441  734.48028099   33.91077476]


In [12]:
print(reg.intercept_)
print(reg.coef_)


151.3456553477407
[  37.90031426 -241.96624835  542.42575342  347.70830529 -931.46126093
  518.04405547  163.40353476  275.31003837  736.18909839   48.67112488]


In [13]:
y_pred = gdr.predict(X_test)

In [14]:
r2_score(y_test,y_pred)

0.3290782253265605

# How to use Mini batch in sklearn

In [48]:
from sklearn.linear_model import SGDRegressor
sgd = SGDRegressor(learning_rate='constant',eta0=0.08)

In [59]:
batch_size = 75

for i in range(100):
    
    idx = random.sample(range(X_train.shape[0]),batch_size)
    sgd.partial_fit(X_train[idx],y_train[idx])
sgd.coef_

array([  25.37225256, -225.64637534,  526.97775985,  324.80985202,
        -90.4178944 , -126.86663955, -208.51906152,  162.63094939,
        403.51370958,   88.00079219])

In [60]:
sgd.intercept_

array([150.05240913])

In [61]:
sgd.coef_

array([  25.37225256, -225.64637534,  526.97775985,  324.80985202,
        -90.4178944 , -126.86663955, -208.51906152,  162.63094939,
        403.51370958,   88.00079219])

In [62]:
y_pred = sgd.predict(X_test)

In [63]:
r2_score(y_test,y_pred)

0.4597661032841541